Repository angr/cle, pull requests merged in 2019-07, with the labels that each got.

#196 Clemory.load(): Raise a KeyError with the missing addr instead of size.
  cle/memory.py
Labels: bug

#195 Clarify Backend.has_memory. Make sure all backend objects appear in all_objects.
  cle/backends/__init__.py
  cle/backends/java/soot.py
  cle/loader.py
Labels: refactor

#198 Remove unusable idabin backend
  cle/backends/idabin.py
  setup.py
Labels: refactor

#199 Do not crash if we encounter problems when importing BinjaBin.
  cle/backends/__init__.py
Labels: enhancement

#197 Add permissions to NamedRegions
  cle/backends/named_region.py
  cle/backends/region.py
Labels: feature

#200 Resiliency against incorrect IMAGE_REL_BASED_DIR64 reloc entries.
  cle/backends/pe/relocation/generic.py
Labels: enhancement

#201 PE reloc: Do not calculate relocations twice.
  cle/backends/pe/relocation/pereloc.py
Labels: enhancement
